
tasks:
  - init: yarn
    command: |
      yarn
      gem install compass  # this doesn't seem to stick if done in init
      yarn start

ports:
  - port: 9000
    onOpen: open-preview

vscode:
  extensions:
    - esbenp.prettier-vscode